### ISSUE TITLE
Issue upgrading from 0.5.2

### ISSUE THREAD

**Issue by kennethkalmer** [luminus-framework/conman#20]
I'm not quite sure what in fce1c016dd6086 causes the issue, but we've been having a fight here today in a luminus project.

AFAICT `datasource-config` in [make-config](https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L47) is being called multiple times. In latter calls the `pool-spec` value is null, blowing up `hikari-cp.core/validate-options`.

To reproduce with luminus (2.9.10.50), simply generate a new project with `+postgres` and then add `[app.db.core :as db]` to the home handler and boot the app up. Alternatively start a `lein repl` and call `(conman/connect! {...})` manually.

 It should fail with the following exception: `java.lang.IllegalArgumentException: Invalid configuration options: (:driver-class-name)`, because the pool-spec is null.

We confirmed this on two different dev machines.

Let me know if I can provide more information.

**Comment by lenw** [comment]
Confirmed that we are seeing this.

**Comment by yogthos** [comment]
Yup, I can confirm I'm seeing this as well. Sorry for the inconvenience, I'll have this fixed in a bit.

**Comment by yogthos** [comment]
I just pushed out a new version `0.5.6` that should fix the issue.

**Comment by lenw** [comment]
testing now 
- update deps to 0.5.6 and still see the error 
  @kennethkalmer do you see it fixed ?

**Comment by yogthos** [comment]
Ah ok, I can see another problem there. I tested using a datasource directly, but looks like using `:jdbc-url` alone is not sufficient. Just testing a fix right now.

**Comment by yogthos** [comment]
Just pushed out `0.5.7`, it looks like the hikari-cp library requites that the `driver-class-name` key is present when using the `jdbc-url` key. However, this isn't required by the HikariCP library. I've updated conman to handle this and opened an issue in the upstream project.

Let me know if this looks good. I tested locally with Postgres and seems to be working as expected.

**Comment by kennethkalmer** [comment]
So far `0.5.7` is working well 🍻

**Comment by yogthos** [comment]
Fantastic, sorry about the screw up there, I should've done a bit more testing before pushing it out.

**Comment by yogthos** [comment]
@lenw could we close this one?

**Comment by lenw** [comment]
Confirmed its working thanks @yogthos
